spring:
  cloud:
    # 网关配置
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        # 商品管理中心
        - id: youngtao_gmc_route
          uri: lb://youngtao-gmc-serve
          predicates:
            - Path=/gmc/**
          filters:
            - StripPrefix=1

# 不需要token的url
youngtao:
  skip_path:
    - /api/oauth/login
    - /api/**
    - /**
